### ISSUE TITLE
parents guide

### ISSUE THREAD

**Issue by twhitbeck** [BharatKalluri/MovieScore#3]
Was going to ask for a feature: IMDB's Parent's Guide.

Then I found this:
http://theimdbapi.betaeasy.com/thread/4993

If/when that gets implemented, I'd love to see it in here.

**Comment by BharatKalluri** [comment]
Hey @twhitbeck !

Thanks for the suggestion! The Parental guide is implemented and functional.

As a temporary solution I am getting the parental guide from the website itself, when it well get implemented in the api, I will change the source back to the api for the information.

For a demo, watch the updated video(asciinema)
